Unit test for classes
cilfonegabriel/OOP-school-library pull request #8
Opened 2023-03-22 20:48 UTC by cilfonegabriel

# Dear Code Reviewers.
## Could I ask you for your kindly support to review my Project? 🙏

### Project requirements
- Add unit tests for all the methods in all the classes:
  - `Book`
  - `Person`
  - `Student`
  - `Teacher`
  - `Classroom`
  - `Rental`
  - `Nameable`
  - `CapitalizeDecorator`
  - `Decorator`

### Thank´s Gabriel!

2023-03-22 21:47 UTC, Whoistolu reviewed
Hi @cilfonegabriel 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a pair-programming project, that should have contributions from you and your partner(s) but you are the only developer who has contributed to this project. As much as I understand that your partner dropped off, it is required to get approval to work alone from the student success team and attach a screenshot of the response to your PR description.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-22 22:11 UTC, rmrmrmr commented
## Hi @Whoistolu and future code reviewer!
I can validate that although this project is marked as pair-programming @cilfonegabriel is working solo. I was assigned as his coding partner at the beginning of the week, but it was only temporary since I moved on to the next one. We had no other partners so he can't include commits of any other non-existing micronauts! 😝 
 Here are some links to the [repo I've been working on](https://github.com/Gdiazdiaz/Capstone-catalogue-of-my-things) and to some[ pull requests I've opened there](https://github.com/Gdiazdiaz/Capstone-catalogue-of-my-things/pull/36) so you can assess that indeed I'm no longer his coding partner.

2023-03-22 22:56 UTC, BenMukebo requested changes
### Hi @cilfonegabriel,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- All test files is placed in a different directory. ✔️  
- Gitflow was correctly used.✔️ 
- All tests are passing. 🥇 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL ] Use descriptive commit messages.  The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Example:
  - :x: Wrong: added Descriptive README
  - :heavy_check_mark: Right: Add descriptive README

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 22:56 UTC, BenMukebo commented on spec/person_spec.rb
> +        'id' => '1234-5678',
- [ ] Great job so far 👏🏻 👏🏻 However, according to the project requirements, there should be unit tests for all the methods in all the classes, Kindly make sure the `of_age?, correct_name and add_rental` class person method has (at least) an 'it' block 👇🏻 check your person.rb file

```ruby
 def of_age?
    @age > 18
  end

  def correct_name
    @name
  end

  def add_rental(book, date = Date.today)
    @rentals.push(Rental.new(date, self, book))
  end
```

2023-03-22 22:56 UTC, BenMukebo commented on spec/decorator_spec.rb
> +  it 'returns a nameable object' do
- [ ] Kindly make sure to add unit tests for all the methods of the: `Decorator class` ✍🏻 Cureent you're missing the `correct_name` method tests. 👇🏻  


```ruby
  def correct_name
    @nameable.correct_name
  end
```

2023-03-22 23:42 UTC, Reem-lab requested changes
# Hi Team, 👋🏻👋🏻

Great work on making the changes requested by a previous reviewer 👏💯🔥✨🤩🤩 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>



 ## Highlights
- No Linters error ✨🤩
- Great working on the tests ✨💯
- Followed Gitflow 🤩🔥🔥

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 23:42 UTC, Reem-lab commented on spec/person_spec.rb
> +    end
- [ ] Great on working on the changes that requested from the previous reviewer but I think you miss understand what he asked you, in Person you missed to add tests to the methods that he mentioned `of_age?, correct_name and add_rental` so great you added for `correct_name` but you still missed to test the another two methods and he said that (at least) an 'it' block 👇🏻  but it block for each method so at least one test for each method not at least one method 🙏🏻✅💯🤩 so kindly add tests for the another methods  `of_age? and add_rental` 💪🏻

2023-03-23 14:35 UTC, danmainah approved these changes
Hi @cilfonegabriel , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Gitflow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 14:38 UTC, merged